<?php 
Category::create([
    'name' => 'Programming', 
    'slug' => 'programming'
]);
Category::create([
    'name' => 'Web Design', 
    'slug' => 'web-design'
]);
Category::create([
    'name' => 'Personal', 
    'slug' => 'personal'
]);

Post::create([
    'title' => 'Judul Pertama', 
    'category_id' => 1,
    'slug' => 'judul-pertama',
    'excerpt' => 'Lorem ipsum pertama',
    'body' => '<p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Illo reiciendis animi placeat! Soluta natus explicabo quae tempore suscipit iste! Tempore at, accusantium rem fugit temporibus iure voluptates, vel pariatur suscipit provident, illo accusamus repellat laudantium qui nulla laboriosam illum mollitia ut in veritatis? Fuga, iusto. Velit architecto voluptatibus quas illo cum? Sint error eum consequatur, explicabo dolores alias eaque perspiciatis ut quam asperiores, distinctio doloremque nisi consequuntur nam porro magnam, eos nihil dolorum officia iste.</p><p>Et itaque aperiam, cum corrupti, nihil minima tempora nobis assumenda unde suscipit asperiores fugit cumque. Quo neque, fugiat cumque numquam ut odio assumenda ratione illo accusamus sed porro consequuntur praesentium officiis nesciunt. Itaque fugiat molestias assumenda tenetur doloremque nisi, consequatur dicta provident voluptas architecto nihil.</p><p>Laborum veniam, quod enim, voluptatibus, dolores sunt expedita ullam facilis laboriosam facere quis et quaerat dolore vero voluptatem aliquid sint. Quidem incidunt non quod, excepturi facere dolorem nam, quo quam similique a corporis corrupti recusandae consequatur, dolores hic. Hic aspernatur repellendus voluptas tenetur assumenda alias harum placeat distinctio fugiat. Ipsa accusantium, esse cupiditate aperiam consequatur odio quae similique sunt quas ea illo veniam libero laborum dolore, dignissimos placeat inventore, ut distinctio labore voluptatum accusamus. Sed maxime odio, harum repellendus illo assumenda deserunt quas delectus explicabo et incidunt doloremque facilis itaque distinctio accusamus, laborum ipsum in, eum corporis. Deserunt voluptatum quis magnam deleniti, illo nesciunt fugit repudiandae veritatis, nostrum nam, praesentium vitae tenetur nemo! Quos nostrum facere, excepturi eligendi omnis quaerat porro at, aut nisi temporibus vero quod ratione fuga, quas non dolorem.</p><p>Ut illo voluptatem eius. Explicabo corrupti perferendis, deleniti incidunt earum eius rerum aliquid id quibusdam? Qui, dolore impedit odio nisi nostrum at tenetur repellat est soluta minus provident quos earum culpa voluptatum magnam deleniti corporis veniam natus officiis eius aspernatur! Error dolorem optio cumque rerum veritatis eum modi?</p>'
]);
Post::create([
    'title' => 'Judul Ke Dua', 
    'category_id' => 2,
    'slug' => 'judul-ke-dua',
    'excerpt' => 'Lorem ipsum ke dua',
    'body' => '<p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Illo reiciendis animi placeat! Soluta natus explicabo quae tempore suscipit iste! Tempore at, accusantium rem fugit temporibus iure voluptates, vel pariatur suscipit provident, illo accusamus repellat laudantium qui nulla laboriosam illum mollitia ut in veritatis? Fuga, iusto. Velit architecto voluptatibus quas illo cum? Sint error eum consequatur, explicabo dolores alias eaque perspiciatis ut quam asperiores, distinctio doloremque nisi consequuntur nam porro magnam, eos nihil dolorum officia iste.</p><p>Et itaque aperiam, cum corrupti, nihil minima tempora nobis assumenda unde suscipit asperiores fugit cumque. Quo neque, fugiat cumque numquam ut odio assumenda ratione illo accusamus sed porro consequuntur praesentium officiis nesciunt. Itaque fugiat molestias assumenda tenetur doloremque nisi, consequatur dicta provident voluptas architecto nihil.</p><p>Laborum veniam, quod enim, voluptatibus, dolores sunt expedita ullam facilis laboriosam facere quis et quaerat dolore vero voluptatem aliquid sint. Quidem incidunt non quod, excepturi facere dolorem nam, quo quam similique a corporis corrupti recusandae consequatur, dolores hic. Hic aspernatur repellendus voluptas tenetur assumenda alias harum placeat distinctio fugiat. Ipsa accusantium, esse cupiditate aperiam consequatur odio quae similique sunt quas ea illo veniam libero laborum dolore, dignissimos placeat inventore, ut distinctio labore voluptatum accusamus. Sed maxime odio, harum repellendus illo assumenda deserunt quas delectus explicabo et incidunt doloremque facilis itaque distinctio accusamus, laborum ipsum in, eum corporis. Deserunt voluptatum quis magnam deleniti, illo nesciunt fugit repudiandae veritatis, nostrum nam, praesentium vitae tenetur nemo! Quos nostrum facere, excepturi eligendi omnis quaerat porro at, aut nisi temporibus vero quod ratione fuga, quas non dolorem.</p><p>Ut illo voluptatem eius. Explicabo corrupti perferendis, deleniti incidunt earum eius rerum aliquid id quibusdam? Qui, dolore impedit odio nisi nostrum at tenetur repellat est soluta minus provident quos earum culpa voluptatum magnam deleniti corporis veniam natus officiis eius aspernatur! Error dolorem optio cumque rerum veritatis eum modi?</p>'
]);
Post::create([
    'title' => 'Judul Ke Tiga', 
    'category_id' => 3,
    'slug' => 'judul-ke-tiga',
    'excerpt' => 'Lorem ipsum ke tiga',
    'body' => '<p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Illo reiciendis animi placeat! Soluta natus explicabo quae tempore suscipit iste! Tempore at, accusantium rem fugit temporibus iure voluptates, vel pariatur suscipit provident, illo accusamus repellat laudantium qui nulla laboriosam illum mollitia ut in veritatis? Fuga, iusto. Velit architecto voluptatibus quas illo cum? Sint error eum consequatur, explicabo dolores alias eaque perspiciatis ut quam asperiores, distinctio doloremque nisi consequuntur nam porro magnam, eos nihil dolorum officia iste.</p><p>Et itaque aperiam, cum corrupti, nihil minima tempora nobis assumenda unde suscipit asperiores fugit cumque. Quo neque, fugiat cumque numquam ut odio assumenda ratione illo accusamus sed porro consequuntur praesentium officiis nesciunt. Itaque fugiat molestias assumenda tenetur doloremque nisi, consequatur dicta provident voluptas architecto nihil.</p><p>Laborum veniam, quod enim, voluptatibus, dolores sunt expedita ullam facilis laboriosam facere quis et quaerat dolore vero voluptatem aliquid sint. Quidem incidunt non quod, excepturi facere dolorem nam, quo quam similique a corporis corrupti recusandae consequatur, dolores hic. Hic aspernatur repellendus voluptas tenetur assumenda alias harum placeat distinctio fugiat. Ipsa accusantium, esse cupiditate aperiam consequatur odio quae similique sunt quas ea illo veniam libero laborum dolore, dignissimos placeat inventore, ut distinctio labore voluptatum accusamus. Sed maxime odio, harum repellendus illo assumenda deserunt quas delectus explicabo et incidunt doloremque facilis itaque distinctio accusamus, laborum ipsum in, eum corporis. Deserunt voluptatum quis magnam deleniti, illo nesciunt fugit repudiandae veritatis, nostrum nam, praesentium vitae tenetur nemo! Quos nostrum facere, excepturi eligendi omnis quaerat porro at, aut nisi temporibus vero quod ratione fuga, quas non dolorem.</p><p>Ut illo voluptatem eius. Explicabo corrupti perferendis, deleniti incidunt earum eius rerum aliquid id quibusdam? Qui, dolore impedit odio nisi nostrum at tenetur repellat est soluta minus provident quos earum culpa voluptatum magnam deleniti corporis veniam natus officiis eius aspernatur! Error dolorem optio cumque rerum veritatis eum modi?</p>'
]);
Post::create([
    'title' => 'Judul Ke Empat', 
    'category_id' => 1,
    'slug' => 'judul-ke-empat',
    'excerpt' => 'Lorem ipsum ke empat',
    'body' => '<p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Illo reiciendis animi placeat! Soluta natus explicabo quae tempore suscipit iste! Tempore at, accusantium rem fugit temporibus iure voluptates, vel pariatur suscipit provident, illo accusamus repellat laudantium qui nulla laboriosam illum mollitia ut in veritatis? Fuga, iusto. Velit architecto voluptatibus quas illo cum? Sint error eum consequatur, explicabo dolores alias eaque perspiciatis ut quam asperiores, distinctio doloremque nisi consequuntur nam porro magnam, eos nihil dolorum officia iste.</p><p>Et itaque aperiam, cum corrupti, nihil minima tempora nobis assumenda unde suscipit asperiores fugit cumque. Quo neque, fugiat cumque numquam ut odio assumenda ratione illo accusamus sed porro consequuntur praesentium officiis nesciunt. Itaque fugiat molestias assumenda tenetur doloremque nisi, consequatur dicta provident voluptas architecto nihil.</p><p>Laborum veniam, quod enim, voluptatibus, dolores sunt expedita ullam facilis laboriosam facere quis et quaerat dolore vero voluptatem aliquid sint. Quidem incidunt non quod, excepturi facere dolorem nam, quo quam similique a corporis corrupti recusandae consequatur, dolores hic. Hic aspernatur repellendus voluptas tenetur assumenda alias harum placeat distinctio fugiat. Ipsa accusantium, esse cupiditate aperiam consequatur odio quae similique sunt quas ea illo veniam libero laborum dolore, dignissimos placeat inventore, ut distinctio labore voluptatum accusamus. Sed maxime odio, harum repellendus illo assumenda deserunt quas delectus explicabo et incidunt doloremque facilis itaque distinctio accusamus, laborum ipsum in, eum corporis. Deserunt voluptatum quis magnam deleniti, illo nesciunt fugit repudiandae veritatis, nostrum nam, praesentium vitae tenetur nemo! Quos nostrum facere, excepturi eligendi omnis quaerat porro at, aut nisi temporibus vero quod ratione fuga, quas non dolorem.</p><p>Ut illo voluptatem eius. Explicabo corrupti perferendis, deleniti incidunt earum eius rerum aliquid id quibusdam? Qui, dolore impedit odio nisi nostrum at tenetur repellat est soluta minus provident quos earum culpa voluptatum magnam deleniti corporis veniam natus officiis eius aspernatur! Error dolorem optio cumque rerum veritatis eum modi?</p>'
]);